# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VWODemoApp' do
  use_frameworks!
  pod 'SlideMenuControllerSwift'
  pod 'VWO', '2.0.0-beta1'
  pod 'FLEX', '~> 2.0'

end
