# platform :ios, '9.0'

target 'VWO Demo' do
  use_frameworks!
  
  pod 'VWO', :path => '../'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  
  target 'VWO DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
