# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VWO Demo' do
  use_frameworks!
   #pod 'VWO', '~> 2.7.1'
   pod 'VWO', :path => '../'
   pod 'SCLAlertView', '~> 0.8'
   pod 'MBProgressHUD', '~> 1.1.0'

end
