# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'VWO Demo' do
  use_frameworks!
  pod 'VWO', :path => '../'
#  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'SCLAlertView'

end
